In [1]:
from neural_network import NeuralNetwork
from sgd import SGD
from quickprop import Quickprop
from rprop import Rprop
from lr_schedulers import ExponentialDecayScheduler, TimeBasedScheduler, StepDecayScheduler
import numpy as np
from sklearn.metrics import accuracy_score
#MONK1 PROBLEM

train_set = np.genfromtxt("../cup/ML-CUP18-TR.csv", delimiter=",")[:, 1:-2]
train_targets = np.genfromtxt("../cup/ML-CUP18-TR.csv", delimiter=",")[:, -2:]

In [2]:
nn = NeuralNetwork()
nn.add_layer('dense', 40, 'sigmoid', train_set.shape[1]) #input layer
nn.add_layer('dense', 40, 'sigmoid')
nn.add_layer('dense', 2, 'linear')
nn.compile(task='Regression', dropout=[0.5, 0.5, 0.5], optimizer=SGD(lr_init=0.0005, momentum=0.9, nesterov=False, lr_sched=StepDecayScheduler(drop=0.95, epochs_drop=100))) #StepDecayScheduler(drop=0.9, epochs_drop=100)

nn.fit(train_set, train_targets, batch_size=64, test_size=0.3, epochs=5000, patience=200, save_pred="esempio", verbose=True) #lr=0.05 test_size=0.5 epochs=2000

loss improved at epoch 1 :  [19.43164915]
loss improved at epoch 2 :  [10.77141424]
loss improved at epoch 3 :  [7.11788368]
loss improved at epoch 4 :  [4.70904361]
loss improved at epoch 5 :  [3.73315637]
loss improved at epoch 6 :  [3.21364315]
loss improved at epoch 7 :  [2.74306464]
loss improved at epoch 8 :  [2.33543337]
loss improved at epoch 9 :  [2.19512142]
loss improved at epoch 10 :  [2.0378831]
loss improved at epoch 11 :  [1.97449312]
loss improved at epoch 12 :  [1.89404117]
loss improved at epoch 13 :  [1.84135629]
loss improved at epoch 14 :  [1.80578912]
loss improved at epoch 15 :  [1.79662098]
loss improved at epoch 17 :  [1.75300818]
loss improved at epoch 18 :  [1.70442996]
loss improved at epoch 19 :  [1.67269171]
loss improved at epoch 20 :  [1.60974567]
loss improved at epoch 21 :  [1.60187593]
loss improved at epoch 22 :  [1.5640174]
loss improved at epoch 23 :  [1.55899689]
loss improved at epoch 24 :  [1.55189527]
loss improved at epoch 25 :  [1.50740584]
l

(<neural_network.NeuralNetwork at 0x1f7b0c4da90>,
 (array([1.02518673]), False, array([False])),
 375)

In [102]:
# 0.94817595 LMS
with open('best_nn_cup.pkl', 'wb') as output:
    pickle.dump(nn, output, pickle.HIGHEST_PROTOCOL)

In [8]:
nn.predict(train_set[:20])

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [6]:
#MONK2 PROBLEM

train_set = np.genfromtxt("../monks/monks2-train.txt", delimiter=" ", dtype="int")[:,1:-1] #rimuove la colonna nan alla fine
train_targets = np.genfromtxt("../monks/monks2-train.txt", delimiter=" ", dtype="int")[:,:1]

test_set = np.genfromtxt("../monks/monks2-test.txt", delimiter=" ", dtype="int") [:,1:-1] #rimuove targets e colonna nan 
test_targets = np.genfromtxt("../monks/monks2-test.txt", delimiter=" ", dtype="int") [:,0:1]

In [91]:
nn = NeuralNetwork()
nn.add_layer('dense', 10, 'sigmoid', train_set.shape[1]) #input layer
nn.add_layer('dense', 100, 'sigmoid') #input layer
nn.add_layer('dense', 1, 'sigmoid')
nn.compile(optimizer=SGD(lr_init=0.1, momentum=0.9, nesterov=False, lr_sched=StepDecayScheduler(drop=0.9, epochs_drop=10)))

nn.fit(train_set, train_targets, batch_size=16, test_size=0.5, epochs=5000, patience=200, save_model='best_nn_monk2_tmp', verbose=True)

ValueError: shapes (16,11) and (10,10) not aligned: 11 (dim 1) != 10 (dim 0)

In [43]:
prediction = nn.predict(test_set)
accuracy_score(test_targets, prediction)

0.7291666666666666

In [143]:
#MONK3 PROBLEM

train_set = np.genfromtxt("../monks/monks3-train.txt", delimiter=" ", dtype="int")[:,1:-1] #rimuove la colonna nan alla fine
train_targets = np.genfromtxt("../monks/monks3-train.txt", delimiter=" ", dtype="int")[:,:1]

test_set = np.genfromtxt("../monks/monks3-test.txt", delimiter=" ", dtype="int") [:,1:-1] #rimuove targets e colonna nan 
test_targets = np.genfromtxt("../monks/monks3-test.txt", delimiter=" ", dtype="int") [:,0:1]

In [225]:
nn = NeuralNetwork()
nn.add_layer('dense', 40, 'sigmoid', train_set.shape[1]) #input layer
nn.add_layer('dense', 30, 'sigmoid') #input layer
nn.add_layer('dense', 1, 'sigmoid')
nn.compile(optimizer=SGD(lr_init=0.25, momentum=0.8, nesterov=False, lr_sched=StepDecayScheduler(drop=0.1, epochs_drop=15)))

nn.fit(train_set, train_targets, batch_size=16, test_size=0.5, epochs=5000, patience=200, save_model='best_nn_monk3_tmp', verbose=True)

Accuracy improved at epoch  1 :  0.5081967213114754
Accuracy improved at epoch  2 :  0.7213114754098361
Accuracy improved at epoch  3 :  0.8032786885245902
Accuracy improved at epoch  6 :  0.8852459016393442
Accuracy improved at epoch  14 :  0.9016393442622951
Accuracy improved at epoch  15 :  0.9344262295081968
Accuracy improved at epoch  30 :  0.9508196721311475


In [226]:
prediction = nn.predict(test_set)
accuracy_score(test_targets, prediction)

0.8680555555555556

In [7]:
import pickle
with open('40units_cup_results.pkl', 'rb') as inputfile:
    res = pickle.load(inputfile)
    res.sort(key=lambda x: x[0])
    for result in res:
        print(result)

(1.2315455289090356, {'activation': 'sigmoid', 'batch_size': 64, 'dropout': [0.5, 0.5, 0.5], 'epoch': 5000, 'l2_lambda': None, 'layers': (40, 40, 2), 'lr': 0.0001, 'lr_sched': <lr_schedulers.StepDecayScheduler object at 0x00000207E5717B00>, 'momentum': 0.9, 'nesterov': True, 'patience': 200, 'test_size': 0.3})
(1.2452818317377465, {'activation': 'sigmoid', 'batch_size': 128, 'dropout': [0.5, 0.5, 0.5], 'epoch': 5000, 'l2_lambda': None, 'layers': (40, 40, 2), 'lr': 0.0001, 'lr_sched': <lr_schedulers.StepDecayScheduler object at 0x00000207E5717B70>, 'momentum': 0.9, 'nesterov': True, 'patience': 200, 'test_size': 0.3})
(1.2514707021326856, {'activation': 'sigmoid', 'batch_size': 64, 'dropout': None, 'epoch': 5000, 'l2_lambda': None, 'layers': (40, 40, 2), 'lr': 0.0005, 'lr_sched': <lr_schedulers.StepDecayScheduler object at 0x00000207E5717B70>, 'momentum': 0.9, 'nesterov': True, 'patience': 200, 'test_size': 0.3})
(1.2558965151036923, {'activation': 'sigmoid', 'batch_size': 64, 'dropout'

In [2]:
train_set = np.genfromtxt("../cup/ML-CUP18-TR.csv", delimiter=",")[:, 1:-2]
train_targets = np.genfromtxt("../cup/ML-CUP18-TR.csv", delimiter=",")[:, -2:]

nn = NeuralNetwork()
nn.add_layer('dense', 40, 'sigmoid', train_set.shape[1]) #input layer
nn.add_layer('dense', 40, 'sigmoid')
nn.add_layer('dense', 2, 'linear')
nn.compile(task='Regression', dropout=[0.5, 0.5, 0.5], optimizer=SGD(lr_init=0.0005, momentum=0.9, nesterov=False, lr_sched=StepDecayScheduler(drop=0.95, epochs_drop=100))) #StepDecayScheduler(drop=0.9, epochs_drop=100)

nn.fit(train_set, train_targets, batch_size=64, test_size=0.3, epochs=5000, patience=200, save_pred="esempio", verbose=False) #lr=0.05 test_size=0.5 epochs=2000

(<neural_network.NeuralNetwork at 0x20fa69937f0>, array([1.20574064]), 676)

In [8]:
#Assumiamo, per comodità, di voler vedere le predizioni all'epoca 20, tanto ci arriva quasi sempre almeno alla 20esima epoca. 
#Intanto carico l'array con np.load. Lavoro solo su vl_pred, tanto tr è uguale
vl_pred = np.load("esempio_vl_predictions.npy")

#Partiamo dal fatto che questi array hanno shape (#epoche, #record, 2*#colonne_target)
#Seleziono l'epoca sul primo indice e continuo solo su vl_pred
epoch_vl_pred = vl_pred[20, :]

#Ora ho una riga per ogni record, non rimane che prendere le predizioni. 
#Sappiamo che la prima metà delle colonne sono i target VERI, mentre la seconda metà sono quelli PREDETTI.
#Siccome siamo informatici di merda, il numero di colonne del target lo becchiamo inferendolo dalla shape del target.

print("Stampo i valori veri")
print(epoch_vl_pred[:, :train_targets.shape[1]]) # Ho preso le colonne da 0 a #colonne_target escluso
print("--------------------------------------")
print("Stampo i valori predetti")
print(epoch_vl_pred[:, train_targets.shape[1]:]) # Ho preso le colonne da #colonne_target fino alla fine

#Ovviamente posso fare un merge di tutta questa roba lavorando solo su vl_pred, solo che seleziono la riga a priori
print("Stampo i valori veri")
print(vl_pred[20, :, :train_targets.shape[1]])
print("--------------------------------------")
print("Stampo i valori predetti")
print(vl_pred[20, :, train_targets.shape[1]:])


(877, 338, 4)
Stampo i valori veri
[[-15.096911 -17.825393]
 [-15.011978 -17.791743]
 [-14.989477 -17.842593]
 [-14.963425 -17.827313]
 [-14.960218 -17.554026]
 [-14.959775 -17.450373]
 [-14.928243 -18.123974]
 [-14.903441 -17.442175]
 [-14.901635 -17.588636]
 [-14.877994 -18.121464]
 [-14.869197 -18.165971]
 [-14.806306 -18.13019 ]
 [-14.78378  -17.209639]
 [-14.763104 -17.337765]
 [-14.702991 -18.236897]
 [-14.699686 -17.016013]
 [-14.64452  -17.157786]
 [-14.598537 -18.437492]
 [-14.578638 -18.27523 ]
 [-14.537761 -18.304429]
 [-14.501055 -18.506276]
 [-14.438561 -16.721616]
 [-14.397624 -16.784375]
 [-14.378458 -16.937735]
 [-14.346866 -18.668425]
 [-14.303346 -16.825736]
 [-14.163837 -18.682155]
 [-14.146146 -16.620402]
 [-14.134705 -18.711811]
 [-14.092061 -18.706177]
 [-14.030127 -16.362968]
 [-14.026246 -18.8851  ]
 [-14.006701 -16.358265]
 [-13.971826 -18.968998]
 [-13.891836 -16.333172]
 [-13.837943 -19.071024]
 [-13.816601 -19.087402]
 [-13.806025 -16.170131]
 [-13.73007  -1