In [280]:
from neural_network import NeuralNetwork
from sgd import SGD
from quickprop import Quickprop
from rprop import Rprop
from lr_schedulers import ExponentialDecayScheduler, TimeBasedScheduler, StepDecayScheduler
import numpy as np
from losses import lms
from sklearn.metrics import accuracy_score
import random
import time
#MONK1 PROBLEM

train_set = np.genfromtxt("../cup/ML-CUP18-TR.csv", delimiter=",")[:, 1:-2]
train_targets = np.genfromtxt("../cup/ML-CUP18-TR.csv", delimiter=",")[:, -2:]


In [281]:
loss = 100
nn = NeuralNetwork()
nn.add_layer('dense', 120, 'sigmoid', train_set.shape[1])
nn.add_layer('dense', 120, 'sigmoid')
nn.add_layer('dense', 2, 'linear')
nn.compile(task='Regression', l2_lambda=1e-9, optimizer=SGD(lr_init=0.00075, momentum=0.9, nesterov=False, lr_sched=StepDecayScheduler(drop=0.95, epochs_drop=100)))

start = time.time()
nn, loss ,_ = nn.fit(train_set, train_targets, batch_size=64, test_size=0.3, epochs=5000, patience=150, save_model='final_cup_nn', save_pred='final_cup_pred', verbose=True)
stop = time.time()

loss improved at epoch 1 :  [6.66179311]
loss improved at epoch 2 :  [5.50077142]
loss improved at epoch 3 :  [2.87029789]
loss improved at epoch 4 :  [1.67383234]
loss improved at epoch 5 :  [1.57561199]
loss improved at epoch 6 :  [1.47897939]
loss improved at epoch 8 :  [1.47160487]
loss improved at epoch 16 :  [1.29525797]
loss improved at epoch 21 :  [1.28561037]
loss improved at epoch 26 :  [1.2761562]
loss improved at epoch 28 :  [1.24414354]
loss improved at epoch 29 :  [1.23667085]
loss improved at epoch 32 :  [1.22199292]
loss improved at epoch 60 :  [1.17542694]


In [283]:
(stop-start)/210

0.030690736997695197

In [272]:
nn = NeuralNetwork()
nn.add_layer('dense', 40, 'sigmoid', train_set.shape[1])
nn.add_layer('dense', 40, 'sigmoid')
nn.add_layer('dense', 2, 'linear')
nn.compile(task='Regression', optimizer=SGD(lr_init=0.0005, momentum=0.9, nesterov=False, lr_sched=StepDecayScheduler(drop=0.95, epochs_drop=100)))

nn, loss ,_ = nn.fit(train_set, train_targets, batch_size=64, test_size=0.3, epochs=5000, patience=150, save_model='40_cup_nn', save_pred='40_cup_pred', verbose=True)

loss improved at epoch 1 :  [13.81149928]
loss improved at epoch 2 :  [7.64492243]
loss improved at epoch 3 :  [3.03950143]
loss improved at epoch 4 :  [2.70154811]
loss improved at epoch 5 :  [2.3602667]
loss improved at epoch 6 :  [1.73653654]
loss improved at epoch 8 :  [1.48977922]
loss improved at epoch 10 :  [1.41139477]
loss improved at epoch 12 :  [1.37787069]
loss improved at epoch 19 :  [1.36631927]
loss improved at epoch 37 :  [1.34066882]
loss improved at epoch 43 :  [1.33480754]
loss improved at epoch 47 :  [1.33011647]
loss improved at epoch 48 :  [1.31444697]
loss improved at epoch 71 :  [1.31415374]
loss improved at epoch 74 :  [1.30638381]
loss improved at epoch 75 :  [1.28888833]
loss improved at epoch 100 :  [1.28436417]
loss improved at epoch 126 :  [1.24607999]
loss improved at epoch 173 :  [1.24579897]
loss improved at epoch 209 :  [1.24473656]


In [181]:
nn2 = NeuralNetwork()
nn2.add_layer('dense', 40, 'sigmoid', train_set.shape[1])
nn2.add_layer('dense', 40, 'sigmoid')
nn2.add_layer('dense', 2, 'linear')
nn2.compile(task='Regression', l2_lambda=None, optimizer=SGD(lr_init=0.0005, momentum=0.9, nesterov=False, lr_sched=StepDecayScheduler(drop=0.95, epochs_drop=100)))

nn2, loss ,_ = nn2.fit(train_set, train_targets, batch_size=64, test_size=0.3, epochs=5000, patience=150, save_model=None, save_pred=None, verbose=True)

loss improved at epoch 1 :  [16.60662597]
loss improved at epoch 2 :  [10.47589801]
loss improved at epoch 3 :  [3.78091281]
loss improved at epoch 4 :  [2.79747972]
loss improved at epoch 5 :  [2.11530271]
loss improved at epoch 6 :  [1.77606936]
loss improved at epoch 7 :  [1.43181498]
loss improved at epoch 9 :  [1.3268438]
loss improved at epoch 10 :  [1.31004174]
loss improved at epoch 13 :  [1.2582478]
loss improved at epoch 15 :  [1.25016999]
loss improved at epoch 19 :  [1.20477109]
loss improved at epoch 33 :  [1.17525366]
loss improved at epoch 80 :  [1.16247762]


In [253]:
from grid_search import GridSearch
import numpy as np
import sys

train_set = np.genfromtxt("../cup/ML-CUP18-TR.csv", delimiter=",")[:, 1:-2]
train_targets = np.genfromtxt("../cup/ML-CUP18-TR.csv", delimiter=",")[:, -2:]

layers = [(120, 120, 2)]
param_grid = {
    'layers': layers,
    'activation': ['sigmoid'],
    'lr': [0.00075],
    'l2_lambda': [1e-9],
    'epoch': [5000],
    'patience': [200],
    'test_size': [0.3],
    'batch_size': [64],
    'momentum': [0.9],
    'dropout': [None],
    'nesterov': [False],
    'lr_sched': [(0.95, 100)]
}

gs = GridSearch(task='Regression', tuning_params=param_grid, restarts=10)
res = gs.fit(train_set, train_targets, checkpoints='../cup/120_1e-9_cup_results')


In [284]:
with open('../cup/120_1e-9_cup_results.pkl', 'rb') as file:
    file_res = pickle.load(file)
print(np.mean(file_res[0]['metric_stats']))
file_res[0]

1.2601842327574024


{'params': {'activation': 'sigmoid',
  'batch_size': 64,
  'dropout': None,
  'epoch': 5000,
  'l2_lambda': 1e-09,
  'layers': (120, 120, 2),
  'lr': 0.00075,
  'lr_sched': (0.95, 100),
  'momentum': 0.9,
  'nesterov': False,
  'patience': 200,
  'test_size': 0.3},
 'metric_stats': [array([1.35191221]),
  array([1.13629974]),
  array([1.29234075])],
 'test_stats': [[1.35191220912402], [1.136299742317672], [1.2923407468305148]],
 'vl_stats': [[0.9508148292752369],
  [1.1031889136709372],
  [1.0744502301347165]],
 'tr_stats': [[0.676252166198938], [0.6168638824701349], [0.5865691494842915]]}

In [254]:
print(np.mean(res[0]['metric_stats']))
res[0]

1.2601842327574024


{'params': {'activation': 'sigmoid',
  'batch_size': 64,
  'dropout': None,
  'epoch': 5000,
  'l2_lambda': 1e-09,
  'layers': (120, 120, 2),
  'lr': 0.00075,
  'lr_sched': (0.95, 100),
  'momentum': 0.9,
  'nesterov': False,
  'patience': 200,
  'test_size': 0.3},
 'metric_stats': [array([1.35191221]),
  array([1.13629974]),
  array([1.29234075])],
 'test_stats': [[1.35191220912402], [1.136299742317672], [1.2923407468305148]],
 'vl_stats': [[0.9508148292752369],
  [1.1031889136709372],
  [1.0744502301347165]],
 'tr_stats': [[0.676252166198938], [0.6168638824701349], [0.5865691494842915]]}

In [185]:
import pickle

with open('../cup/final_cup_nn.pkl', 'rb') as inputfile:
    final_nn = pickle.load(inputfile)

final_test_set = np.genfromtxt("../cup/ML-CUP18-TS.csv", delimiter=",")[:, 1:]

In [204]:
final_test_set

array([[ 0.53924 , -1.348691, -0.030658, ...,  0.580333, -1.102281,
         1.800887],
       [-1.362204, -0.877403, -0.855729, ..., -1.323375,  0.930714,
        -1.05985 ],
       [-0.587542,  0.630721, -0.580706, ..., -1.323375,  0.811126,
        -1.231494],
       ...,
       [-0.305847,  0.159432, -0.305682, ..., -0.490503,  0.452362,
        -0.487703],
       [ 0.609663,  1.856072, -0.214007, ...,  0.639824,  0.27298 ,
         0.198874],
       [ 0.18712 ,  1.856072,  0.977762, ...,  0.401861,  0.213186,
        -0.373273]])

In [232]:
np.set_printoptions(suppress=True)
prediction = final_nn.predict(final_test_set)
prediction = np.concatenate([np.expand_dims(np.arange(1, prediction.shape[0]+1), axis=1), prediction], axis=1)
prediction

array([[  1.        ,  -2.30974223, -29.06060997],
       [  2.        ,  -4.31868845,  -4.9211973 ],
       [  3.        ,  -7.28614801,  -8.53666394],
       [  4.        ,  -1.97975306, -29.30438375],
       [  5.        ,  -5.86263667, -25.50160548],
       [  6.        ,  -9.51721092, -11.14408106],
       [  7.        ,  -4.59855142,  -5.30947258],
       [  8.        , -13.37985811, -19.49299267],
       [  9.        ,  -8.1658817 , -24.02491743],
       [ 10.        ,  -7.50033895, -24.55791258],
       [ 11.        ,  -7.64578206,  -8.84247206],
       [ 12.        , -14.43147967, -16.87027108],
       [ 13.        ,  -6.45573977, -25.46630735],
       [ 14.        , -12.71262685, -14.85507625],
       [ 15.        ,  -4.71540633, -27.00604309],
       [ 16.        ,  -5.47740556,  -6.18085374],
       [ 17.        ,  -6.49532728,  -7.42539016],
       [ 18.        , -14.70107781, -18.00153789],
       [ 19.        ,  -3.11208515, -28.35614963],
       [ 20.        ,  -7.35091

In [233]:
np.savetxt("prediction.csv", prediction,
           header="Remo Andreoli, Valerio De Caro\nFresh ML\nML-CUP18\n30/01/2019", fmt=['%d', '%f','%f'] , delimiter=',')

In [236]:
with open('../cup/30_cup_results.pkl', 'rb') as inputfile:
    loaded = pickle.load(inputfile)
loaded[0]

{'params': {'activation': 'sigmoid',
  'batch_size': 128,
  'dropout': None,
  'epoch': 5000,
  'l2_lambda': None,
  'layers': (30, 60, 2),
  'lr': 0.0001,
  'lr_sched': (1, 1),
  'momentum': 0.9,
  'nesterov': True,
  'patience': 200,
  'test_size': 0.3},
 'metric_stats': [array([1.35635569]),
  array([1.19047449]),
  array([1.15917406])],
 'test_stats': [[1.3563556868074114],
  [1.1904744874009208],
  [1.1591740624652629]],
 'vl_stats': [[0.9400775141133103], [1.2417187232588645], [0.869611327559919]],
 'tr_stats': [[0.8310167092387394],
  [0.9106565209445316],
  [0.9566391351164342]],
 'fold_sizes': []}