In [1]:
from neural_network import NeuralNetwork
from sgd import SGD
from quickprop import Quickprop
from rprop import Rprop
from lr_schedulers import ExponentialDecayScheduler, TimeBasedScheduler, StepDecayScheduler
import numpy as np
from sklearn.metrics import accuracy_score
#MONK1 PROBLEM

train_set = np.genfromtxt("../cup/ML-CUP18-TR.csv", delimiter=",")[:, 1:-2]
train_targets = np.genfromtxt("../cup/ML-CUP18-TR.csv", delimiter=",")[:, -2:]

In [2]:
nn = NeuralNetwork()
nn.add_layer('dense', 40, 'sigmoid', train_set.shape[1]) #input layer
nn.add_layer('dense', 40, 'sigmoid')
nn.add_layer('dense', 2, 'linear')
nn.compile(task='Regression', dropout=[0.5, 0.5, 0.5], optimizer=SGD(lr_init=0.0005, momentum=0.9, nesterov=False, lr_sched=StepDecayScheduler(drop=0.95, epochs_drop=100))) #StepDecayScheduler(drop=0.9, epochs_drop=100)

nn.fit(train_set, train_targets, batch_size=64, test_size=0.3, epochs=5000, patience=200, save_pred="esempio", verbose=True) #lr=0.05 test_size=0.5 epochs=2000

loss improved at epoch 1 :  [19.43164915]
loss improved at epoch 2 :  [10.77141424]
loss improved at epoch 3 :  [7.11788368]
loss improved at epoch 4 :  [4.70904361]
loss improved at epoch 5 :  [3.73315637]
loss improved at epoch 6 :  [3.21364315]
loss improved at epoch 7 :  [2.74306464]
loss improved at epoch 8 :  [2.33543337]
loss improved at epoch 9 :  [2.19512142]
loss improved at epoch 10 :  [2.0378831]
loss improved at epoch 11 :  [1.97449312]
loss improved at epoch 12 :  [1.89404117]
loss improved at epoch 13 :  [1.84135629]
loss improved at epoch 14 :  [1.80578912]
loss improved at epoch 15 :  [1.79662098]
loss improved at epoch 17 :  [1.75300818]
loss improved at epoch 18 :  [1.70442996]
loss improved at epoch 19 :  [1.67269171]
loss improved at epoch 20 :  [1.60974567]
loss improved at epoch 21 :  [1.60187593]
loss improved at epoch 22 :  [1.5640174]
loss improved at epoch 23 :  [1.55899689]
loss improved at epoch 24 :  [1.55189527]
loss improved at epoch 25 :  [1.50740584]
l

(<neural_network.NeuralNetwork at 0x1f7b0c4da90>,
 (array([1.02518673]), False, array([False])),
 375)

In [102]:
# 0.94817595 LMS
with open('best_nn_cup.pkl', 'wb') as output:
    pickle.dump(nn, output, pickle.HIGHEST_PROTOCOL)

In [8]:
nn.predict(train_set[:20])

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [6]:
#MONK2 PROBLEM

train_set = np.genfromtxt("../monks/monks2-train.txt", delimiter=" ", dtype="int")[:,1:-1] #rimuove la colonna nan alla fine
train_targets = np.genfromtxt("../monks/monks2-train.txt", delimiter=" ", dtype="int")[:,:1]

test_set = np.genfromtxt("../monks/monks2-test.txt", delimiter=" ", dtype="int") [:,1:-1] #rimuove targets e colonna nan 
test_targets = np.genfromtxt("../monks/monks2-test.txt", delimiter=" ", dtype="int") [:,0:1]

In [91]:
nn = NeuralNetwork()
nn.add_layer('dense', 10, 'sigmoid', train_set.shape[1]) #input layer
nn.add_layer('dense', 100, 'sigmoid') #input layer
nn.add_layer('dense', 1, 'sigmoid')
nn.compile(optimizer=SGD(lr_init=0.1, momentum=0.9, nesterov=False, lr_sched=StepDecayScheduler(drop=0.9, epochs_drop=10)))

nn.fit(train_set, train_targets, batch_size=16, test_size=0.5, epochs=5000, patience=200, save_model='best_nn_monk2_tmp', verbose=True)

ValueError: shapes (16,11) and (10,10) not aligned: 11 (dim 1) != 10 (dim 0)

In [43]:
prediction = nn.predict(test_set)
accuracy_score(test_targets, prediction)

0.7291666666666666

In [143]:
#MONK3 PROBLEM

train_set = np.genfromtxt("../monks/monks3-train.txt", delimiter=" ", dtype="int")[:,1:-1] #rimuove la colonna nan alla fine
train_targets = np.genfromtxt("../monks/monks3-train.txt", delimiter=" ", dtype="int")[:,:1]

test_set = np.genfromtxt("../monks/monks3-test.txt", delimiter=" ", dtype="int") [:,1:-1] #rimuove targets e colonna nan 
test_targets = np.genfromtxt("../monks/monks3-test.txt", delimiter=" ", dtype="int") [:,0:1]

In [225]:
nn = NeuralNetwork()
nn.add_layer('dense', 40, 'sigmoid', train_set.shape[1]) #input layer
nn.add_layer('dense', 30, 'sigmoid') #input layer
nn.add_layer('dense', 1, 'sigmoid')
nn.compile(optimizer=SGD(lr_init=0.25, momentum=0.8, nesterov=False, lr_sched=StepDecayScheduler(drop=0.1, epochs_drop=15)))

nn.fit(train_set, train_targets, batch_size=16, test_size=0.5, epochs=5000, patience=200, save_model='best_nn_monk3_tmp', verbose=True)

Accuracy improved at epoch  1 :  0.5081967213114754
Accuracy improved at epoch  2 :  0.7213114754098361
Accuracy improved at epoch  3 :  0.8032786885245902
Accuracy improved at epoch  6 :  0.8852459016393442
Accuracy improved at epoch  14 :  0.9016393442622951
Accuracy improved at epoch  15 :  0.9344262295081968
Accuracy improved at epoch  30 :  0.9508196721311475


In [226]:
prediction = nn.predict(test_set)
accuracy_score(test_targets, prediction)

0.8680555555555556

In [66]:
import pickle
with open('10units_cup_results.pkl', 'rb') as inputfile:
    res = pickle.load(inputfile)
    res.sort(key=lambda x: np.mean(x['metric_stats']))
    for curr in res:
        for i in range(len(curr['metric_stats'])):
            curr['test_stats'][i][0] = np.mean(curr['test_stats'][i][0])
            curr['vl_stats'][i][0] = np.mean(curr['vl_stats'][i][0])
            curr['tr_stats'][i][0] = np.mean(curr['tr_stats'][i][0])


In [67]:
res

[{'params': {'activation': 'sigmoid',
   'batch_size': 64,
   'dropout': None,
   'epoch': 5000,
   'l2_lambda': None,
   'layers': (10, 20, 2),
   'lr': 0.0001,
   'lr_sched': (0.9, 100),
   'momentum': 0.9,
   'nesterov': True,
   'patience': 200,
   'test_size': 0.3},
  'metric_stats': [array([1.29623788]),
   array([1.35368802]),
   array([1.38424694])],
  'test_stats': [[1.2962378779826826],
   [1.3536880249885674],
   [1.384246937146889]],
  'vl_stats': [[1.0524943228796921],
   [1.0354480626481652],
   [1.093746732468357]],
  'tr_stats': [[0.8956853095145986],
   [1.1158804546929406],
   [0.9149511953267572]],
  'fold_sizes': []},
 {'params': {'activation': 'sigmoid',
   'batch_size': 64,
   'dropout': [0.5, 0.5, 0.5],
   'epoch': 5000,
   'l2_lambda': None,
   'layers': (10, 20, 2),
   'lr': 0.0001,
   'lr_sched': (0.7, 50),
   'momentum': 0.9,
   'nesterov': True,
   'patience': 200,
   'test_size': 0.3},
  'metric_stats': [array([1.4407638]),
   array([1.24036944]),
   array(

In [68]:
np.mean(res[0]['metric_stats'])

1.3447242800393797