In [1]:
from neural_network import NeuralNetwork
from sgd import SGD
from quickprop import Quickprop
from rprop import Rprop
from lr_schedulers import ExponentialDecayScheduler, TimeBasedScheduler, StepDecayScheduler
import numpy as np
from sklearn.metrics import accuracy_score

In [227]:
#MONK1 PROBLEM

train_set = np.genfromtxt("../monks/monks1-train.txt", delimiter=" ", dtype="int")[:,1:-1] #rimuove la colonna nan alla fine
train_targets = np.genfromtxt("../monks/monks1-train.txt", delimiter=" ", dtype="int")[:,:1]

test_set = np.genfromtxt("../monks/monks1-test.txt", delimiter=" ", dtype="int") [:,1:-1] #rimuove targets e colonna nan 
test_targets = np.genfromtxt("../monks/monks1-test.txt", delimiter=" ", dtype="int") [:,0:1]

In [230]:
nn = NeuralNetwork()
nn.add_layer('dense', 15, 'sigmoid', train_set.shape[1]) #input layer
nn.add_layer('dense', 10, 'sigmoid')
nn.add_layer('dense', 1, 'sigmoid')
nn.compile(optimizer=SGD(lr_init=0.1, momentum=0.9, nesterov=True, lr_sched=StepDecayScheduler(drop=0.4, epochs_drop=50)))

nn.fit(train_set, train_targets, batch_size=8, test_size=0.3, epochs=5000, patience=200, save_stats=None, save_model='best_nn_monk1_tmp', verbose=True) #lr=0.05 test_size=0.5 epochs=2000

Accuracy improved at epoch  1 :  0.5
Accuracy improved at epoch  3 :  0.6388888888888888
Accuracy improved at epoch  4 :  0.6666666666666666
Accuracy improved at epoch  10 :  0.9166666666666666
Accuracy improved at epoch  14 :  0.9444444444444444
Accuracy improved at epoch  15 :  0.9722222222222222


In [231]:
prediction = nn.predict(test_set)
accuracy_score(test_targets, prediction)

0.9537037037037037

In [234]:
#MONK2 PROBLEM

train_set = np.genfromtxt("../monks/monks2-train.txt", delimiter=" ", dtype="int")[:,1:-1] #rimuove la colonna nan alla fine
train_targets = np.genfromtxt("../monks/monks2-train.txt", delimiter=" ", dtype="int")[:,:1]

test_set = np.genfromtxt("../monks/monks2-test.txt", delimiter=" ", dtype="int") [:,1:-1] #rimuove targets e colonna nan 
test_targets = np.genfromtxt("../monks/monks2-test.txt", delimiter=" ", dtype="int") [:,0:1]

In [247]:
nn = NeuralNetwork()
nn.add_layer('dense', 10, 'sigmoid', train_set.shape[1]) #input layer
nn.add_layer('dense', 10, 'sigmoid') #input layer
nn.add_layer('dense', 1, 'sigmoid')
nn.compile(optimizer=SGD(lr_init=0.1, momentum=0.8, nesterov=False, lr_sched=StepDecayScheduler(drop=0.9, epochs_drop=10)))

nn.fit(train_set, train_targets, batch_size=16, test_size=0.5, epochs=5000, patience=200, save_model='best_nn_monk2_tmp', verbose=True)

Accuracy improved at epoch  1 :  0.6190476190476191
Accuracy improved at epoch  3 :  0.6309523809523809
Accuracy improved at epoch  35 :  0.6428571428571429


In [43]:
prediction = nn.predict(test_set)
accuracy_score(test_targets, prediction)

0.7291666666666666

In [143]:
#MONK3 PROBLEM

train_set = np.genfromtxt("../monks/monks3-train.txt", delimiter=" ", dtype="int")[:,1:-1] #rimuove la colonna nan alla fine
train_targets = np.genfromtxt("../monks/monks3-train.txt", delimiter=" ", dtype="int")[:,:1]

test_set = np.genfromtxt("../monks/monks3-test.txt", delimiter=" ", dtype="int") [:,1:-1] #rimuove targets e colonna nan 
test_targets = np.genfromtxt("../monks/monks3-test.txt", delimiter=" ", dtype="int") [:,0:1]

In [225]:
nn = NeuralNetwork()
nn.add_layer('dense', 40, 'sigmoid', train_set.shape[1]) #input layer
nn.add_layer('dense', 30, 'sigmoid') #input layer
nn.add_layer('dense', 1, 'sigmoid')
nn.compile(optimizer=SGD(lr_init=0.25, momentum=0.8, nesterov=False, lr_sched=StepDecayScheduler(drop=0.1, epochs_drop=15)))

nn.fit(train_set, train_targets, batch_size=16, test_size=0.5, epochs=5000, patience=200, save_model='best_nn_monk3_tmp', verbose=True)

Accuracy improved at epoch  1 :  0.5081967213114754
Accuracy improved at epoch  2 :  0.7213114754098361
Accuracy improved at epoch  3 :  0.8032786885245902
Accuracy improved at epoch  6 :  0.8852459016393442
Accuracy improved at epoch  14 :  0.9016393442622951
Accuracy improved at epoch  15 :  0.9344262295081968
Accuracy improved at epoch  30 :  0.9508196721311475


In [226]:
prediction = nn.predict(test_set)
accuracy_score(test_targets, prediction)

0.8680555555555556

In [269]:
train_set = np.genfromtxt("../cup/ML-CUP18-TR.csv", delimiter=",")[:, 1:-2]
train_targets = np.genfromtxt("../cup/ML-CUP18-TR.csv", delimiter=",")[:, -2:]

def split_regression(dataset, targets):
    index = np.argsort(targets[:, 0])
    dataset, targets = dataset[index], targets[index]
    indices = [([], []) for _ in range(3)]
    for i in range(0, len(targets), 3):
        for j in range(3):
            if j+3-1 < len(targets):
                for k in range(3):
                    if k == j and j + i < len(targets):
                        indices[j][1].append(i+k)
                    elif k != j:
                        indices[j][0].append(i+k)
    return indices, dataset, targets


In [270]:
indices, ds, ts = split_regression(train_set, train_targets)

In [275]:
ds

array([[ 0.398392,  1.950329,  1.619484, ...,  0.639824,  0.033804,
         0.771022],
       [ 0.257544,  2.044587,  1.436135, ...,  0.34237 , -0.444547,
         0.542163],
       [ 0.53924 ,  0.819237,  2.352881, ...,  0.223388,  0.87092 ,
        -0.258844],
       ...,
       [-0.235423, -1.914238, -0.214007, ..., -0.133557, -1.461045,
         1.457598],
       [-1.221357, -0.311856, -1.222428, ..., -1.085412,  1.050302,
        -1.345924],
       [-0.164999, -1.631465, -0.67238 , ...,  0.520842, -1.341457,
         1.514813]])

In [276]:
ts

array([[-15.096911, -17.825393],
       [-15.07358 , -17.776483],
       [-15.029708, -17.465172],
       ...,
       [ -1.262883, -29.8712  ],
       [ -1.231193,  -1.420463],
       [ -1.164448, -29.923017]])

In [279]:
np.concatenate([train_set, train_targets], axis=1)[train_targets[:, 0] == -15.096911]

array([[  0.398392,   1.950329,   1.619484,   0.656251,   0.932322,
          0.259603,   0.030828,   0.639824,   0.033804,   0.771022,
        -15.096911, -17.825393]])